Repository aztfmod/rovergo, pull requests merged in 2021-06, with the labels that each got.

#27 parse symphony.yml in ci command
  .gitignore
  cmd/ci.go
  go.mod
  pkg/symphony/symphony.go
  samples/.rover.sample.yaml
  samples/sample.symphony.yaml
Labels: symphony-cicd

#41 Implement destroy action for launchpad
  .vscode/launch.json
  cmd/launchpad_run.go
  makefile
  pkg/azure/storage.go
  pkg/landingzone/landingzone.go
  pkg/terraform/terraform.go
Labels: priority 🌟, rover-go

#60 Implement plan/apply/destroy for landingzones
  cmd/cd.go
  cmd/ci.go
  cmd/landingzone.go
  cmd/launchpad.go
  pkg/landingzone/landingzone.go
  pkg/symphony/cd.go
  readme.md
Labels: rover-go
